---
- name: install apache2
  become: true
  hosts: dbservers
  tasks:
    - name: install apache2 on ubuntu server
      apt:
        name: apache2
        state: present

    - name: start the apache2 service
      service:
        name: apache2
        state: started
