---
- name: copy file from src to dest
  become: true
  hosts: all
  tasks:
  - name: copy a file
    copy:    
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: ram
